package nadinee.randomgenerator.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.launch
import nadinee.randomgenerator.data.Repository
import nadinee.randomgenerator.utils.generateNumbers
import kotlin.random.Random

@Composable
fun GeneratorScreen() {
    val context = LocalContext.current
    val snackbarHostState = remember { SnackbarHostState() }
    val scope = rememberCoroutineScope()

    var min by remember { mutableStateOf(1) }
    var max by remember { mutableStateOf(24) }
    var count by remember { mutableStateOf(24) }

    var generated by remember { mutableStateOf(listOf<Int>()) }

    val enabledSpecial = Repository.enabledSpecial

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text("Генератор случайных чисел", fontSize = 24.sp, fontWeight = FontWeight.Bold)

        Spacer(modifier = Modifier.height(24.dp))

        OutlinedTextField(
            value = min.toString(),
            onValueChange = { min = it.toIntOrNull() ?: min },
            label = { Text("От") },
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(modifier = Modifier.height(16.dp))

        OutlinedTextField(
            value = max.toString(),
            onValueChange = { max = it.toIntOrNull() ?: max },
            label = { Text("До") },
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(modifier = Modifier.height(16.dp))

        OutlinedTextField(
            value = count.toString(),
            onValueChange = { count = it.toIntOrNull() ?: count },
            label = { Text("Количество чисел") },
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(modifier = Modifier.height(32.dp))

        Button(
            onClick = {
                if (min >= max || count <= 0 || count > (max - min + 1)) {
                    scope.launch {
                        snackbarHostState.showSnackbar("Проверьте параметры")
                    }
                    return@Button
                }

                generated = generateNumbers(min, max, count, enabledSpecial)
            },
            modifier = Modifier.fillMaxWidth(0.7f)
        ) {
            Text("Сгенерировать", fontSize = 18.sp)
        }

        Spacer(modifier = Modifier.height(32.dp))

        if (generated.isNotEmpty()) {
            Text("Результат:", fontSize = 20.sp, fontWeight = FontWeight.SemiBold)
            Spacer(modifier = Modifier.height(8.dp))
            LazyColumn {
                items(generated) { number ->
                    Text(
                        text = number.toString(),
                        fontSize = 32.sp,
                        modifier = Modifier.padding(8.dp)
                    )
                }
            }
        }
    }
}